#
# Browser app configuration
#

#
# How to start the app
#
start:
  host: 127.0.0.1
  port: 1357
  static_dir: static

#
# Feature configuration
#
features:
  core: {}

  # Our app-local feature!
  user_database: {}
